# Generated by Django 4.1.3 on 2023-01-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_remove_trabajopractico_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajopractico',
            name='datos',
        ),
        migrations.AlterField(
            model_name='trabajopractico',
            name='profesor',
            field=models.CharField(max_length=70),
        ),
    ]
